name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  stats:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@v2
        with:
          username: Shanmugaa2007
          output_path: profile/stats.svg

      - name: Generate Top Languages
        uses: anuraghazra/github-readme-stats@v2
        with:
          username: Shanmugaa2007
          card: top-langs
          output_path: profile/top-langs.svg

      - name: Commit Stats
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/
          git commit -m "chore: update GitHub stats" || exit 0
          git push
